version: 3

vars:
  TAURI_CMD: "cargo tauri"

# output: prefixed

tasks:
  frontend-install:
    desc: Install frontend dependencies
    internal: true
    run: once
    deps:
      - :js:build
    cmd: bun install

  build:
    desc: Build Tauri app for production
    deps:
      - frontend-install
    cmd: "{{.TAURI_CMD}} build"

  dev:
    desc: Run Tauri app in development mode
    deps:
      - frontend-install
    cmd: "{{.TAURI_CMD}} dev"
    interactive: true

  dev:android:
    desc: Run Android app in development mode
    deps:
      - init:android
      - frontend-install
    cmd: "{{.TAURI_CMD}} android dev"
    interactive: true

  init:android:
    desc: Initialize Android environment
    internal: true
    run: once
    status:
      - test -d ./src-tauri/gen/android
    cmd: "{{.TAURI_CMD}} android init"

  test-integration:
    desc: Run desktop integration tests (default)
    aliases: [test-integration:desktop]
    deps:
      - :backend:desktop:build
    dir: ./src-tauri
    env:
      ANY_SYNC_GO_BINARIES_DIR: "{{.ROOT_DIR}}/binaries"
    cmds:
      - cargo test --test integration --features integration-test {{if .TARGET}}--target {{.TARGET}}{{end}} -- --test-threads=1

  test-integration:mobile:
    desc: Run Android integration tests (requires emulator)
    deps:
      - :backend:mobile:build
    dir: ./src-tauri
    env:
      ANY_SYNC_GO_BINARIES_DIR: "{{.ROOT_DIR}}/binaries"
    cmds:
      - cargo ndk test --test integration --features integration-test -t x86_64 -- --test-threads=1
