version: 3

vars:
  TAURI_CMD: "cargo tauri"

tasks:
  frontend-install:
    desc: Install frontend dependencies
    internal: true
    run: once
    deps:
      - :api:build
    cmd: bun install

  build:
    desc: "Build Tauri app for production"
    deps:
      - frontend-install
    cmd: "{{.TAURI_CMD}} build"

  dev:
    desc: "Run Tauri app in development mode"
    deps:
      - frontend-install
      - :backend:desktop:build
    cmd: "{{.TAURI_CMD}} dev"
    interactive: true

  dev:android:
    desc: "Run Android app in development mode"
    deps:
      - init:android
      - :backend:mobile:build:android
      - frontend-install
    cmd: "{{.TAURI_CMD}} android dev"
    interactive: true

  dev:ios:
    desc: "Run iOS app in development mode"
    deps:
      - init:ios
      - :backend:mobile:build:ios
      - frontend-install
    env:
      APPLE_DEVELOPMENT_TEAM: "12345"
    vars:
      SIMULATOR: "iPad mini"
    cmd: "{{.TAURI_CMD}} ios dev '{{.SIMULATOR}}' {{.CLI_ARGS}}"
    interactive: true

  init:android:
    desc: "Initialize Android environment"
    internal: true
    run: once
    status:
      - test -d ./src-tauri/gen/android
    cmd: "{{.TAURI_CMD}} android init"

  init:ios:
    desc: "Initialize iOS environment"
    internal: true
    run: once
    status:
      - test -d ./src-tauri/gen/apple
    cmd: "{{.TAURI_CMD}} ios init"
