version: 3

vars:
  BINARIES_DIR: "{{relPath .TASKFILE_DIR .ROOT_DIR}}/binaries"
  BINARY_PREFIX: any-sync
  OS_MAP:
    map:
      darwin: apple-darwin
      macos: apple-darwin
      linux: unknown-linux-gnu
      windows: pc-windows-msvc
  ARCH_MAP:
    map:
      amd64: x86_64
      arm64: aarch64

tasks:
  build:
    desc: Build desktop binaries
    vars:
      OS: "{{.OS | default OS}}"
      ARCH: "{{.ARCH | default ARCH}}"
      TRIPLE: "{{index .ARCH_MAP .ARCH}}-{{index .OS_MAP .OS}}"
      EXT: '{{if eq .OS "windows"}}.exe{{else}}{{end}}'
      NAME: "{{.BINARY_PREFIX}}-{{.TRIPLE}}{{.EXT}}"
      BINARY: "{{joinPath .BINARIES_DIR .NAME}}"
    label: "{{.TASK}}-{{.OS}}-{{.ARCH}}"
    env:
      GOOS: '{{if eq .OS "macos"}}darwin{{else}}{{.OS}}{{end}}'
      GOARCH: "{{.ARCH}}"
    cmd: go build -o '{{.BINARY}}' ./
    run: when_changed
    sources:
      - ./**/*
      - ../shared/**/*
    generates:
      - "{{.BINARY}}"

  build:*:
    desc: Build desktop binary for specific platform
    deps:
      - for:
          matrix:
            ARCH: [amd64, arm64]
        task: build
        vars:
          OS: "{{index .MATCH 0}}"
          ARCH: "{{.ITEM.ARCH}}"

  build-all:
    desc: Build desktop binary for all platforms
    deps:
      - for:
          matrix:
            OS: [macos, linux, windows]
        task: build:{{.ITEM.OS}}

  test:
    desc: Run Go tests
    cmd: go test ./...

  clean:
    desc: Clean generated binaries
    cmds:
      - rm -rf {{.BINARIES_DIR}}/{{.BINARY_PREFIX}}-*
      - go clean

  mod-tidy:
    desc: Clean and verify Go modules
    cmd: go mod tidy
