version: '3'

includes:
  go:
    taskfile: ./go-backend/Taskfile.yml
    dir: ./go-backend
    alias: backend
  app:
    taskfile: ./examples/tauri-app/Taskfile.yml
    dir: ./examples/tauri-app

tasks:
  ts-install:
    desc: "Install TypeScript dependencies"
    cmd: bun install
    run: once

  ts-build:
    desc: "Build plugin TypeScript API"
    cmd: bun run build
    sources:
      - ./guest-js/*.ts
      - ./package.json
      - ./tsconfig.json
      - ./*.js
    generates:
      - ./dist-js/*

  cargo-build:
    desc: "Build Rust plugin backend"
    dir: examples/tauri-app/src-tauri
    deps:
      - go:build
    cmd: cargo build
    sources:
      - ./src/**/*.rs
      - ./Cargo.toml
      - ./*.rs
    generates:
      - ./target/*

  build:
    desc: "Build all components (backend + mobile)"
    deps:
      - cargo-build
      - ts-build

  build-all:
    desc: "Build all components for all platforms"
    deps:
      - go:build-all
      - build

  # Cleanup
  clean:
    desc: "Clean all build artifacts"
    deps:
      - go:clean
