version: '3'

includes:
  backend:
    taskfile: ./plugin-go-backend/Taskfile.yml
    dir: ./plugin-go-backend
  app:
    taskfile: ./example-app/Taskfile.yml
    dir: ./example-app

tasks:
  ts-install:
    desc: "Install TypeScript dependencies"
    cmd: bun install
    run: once

  ts-build:
    desc: "Build plugin TypeScript API"
    dir: plugin-js-api
    cmd: bun run build
    sources:
      - ./plugin-js-api/src/*.ts
      - ./plugin-js-api/package.json
      - ./plugin-js-api/tsconfig.json
      - ./plugin-js-api/rollup.config.js
    generates:
      - ./plugin-js-api/dist/*

  cargo-build:
    desc: "Build Rust plugin backend"
    dir: example-app/src-tauri
    deps:
      - backend:build
    cmd: cargo build
    sources:
      - ./plugin-rust-core/src/**/*.rs
      - ./plugin-rust-core/Cargo.toml
      - ./plugin-rust-core/build.rs
    generates:
      - ./target/*

  build:
    desc: "Build all components (backend + mobile)"
    deps:
      - cargo-build
      - ts-build

  build-all:
    desc: "Build all components for all platforms"
    deps:
      - backend:build-all
      - build

  # Cleanup
  clean:
    desc: "Clean all build artifacts"
    deps:
      - backend:clean
