version: 3

includes:
  backend:
    taskfile: ./plugin-go-backend/Taskfile.yml
    dir: ./plugin-go-backend
    aliases: [go]
  api:
    taskfile: ./plugin-js-api/Taskfile.yml
    dir: ./plugin-js-api
    aliases: [js]
  core:
    taskfile: ./plugin-rust-core/Taskfile.yml
    dir: ./plugin-rust-core
    aliases: [rust]
  app:
    taskfile: ./example-app/Taskfile.yml
    dir: ./example-app

output: prefixed

env:
  ANY_SYNC_GO_BINARIES_DIR: "{{.ROOT_DIR}}/binaries"

tasks:
  build:
    desc: Build all plugin components
    deps:
      - backend:build
      - core:build
      - api:build

  build-all:
    desc: Build all plugin components for all platforms
    cmds:
      - backend:build-all
      - build

  test:
    desc: Run all tests
    deps:
      - backend:test
      - core:test
      - app:test-integration

  clean:
    desc: Clean all build artifacts
    deps:
      - backend:clean
      - core:clean
      - api:clean
