version: 3

includes:
  go:
    taskfile: ./plugin-go-backend/Taskfile.yml
    dir: ./plugin-go-backend
  app:
    taskfile: ./example-app/Taskfile.yml
    dir: ./example-app

tasks:
  rust:build:
    desc: Build Rust plugin backend
    dir: ./plugin-rust-core
    deps:
      - go:build
    cmd: cargo build
    sources:
      - ./src/**/*.rs
      - ./Cargo.toml
      - ./build.rs
      - "{{.ROOT_DIR}}/plugin-go-backend/desktop/proto/*.proto"
      - "{{.ROOT_DIR}}/binaries/*"
    generates:
      - "{{.ROOT_DIR}}/target/*"

  js:install:
    desc: Install npm dependencies
    dir: ./plugin-js-api
    cmd: bun install
    internal: true
    run: once
    sources:
      - ./package.json

  js:build:
    desc: Build CJS/ESM artifacts
    dir: ./plugin-js-api
    deps:
      - js:install
    cmd: bun run build
    sources:
      - ./src/*.ts
      - ./package.json
    generates:
      - ./dist/*

  build:
    desc: Build all components (backend + mobile)
    deps:
      - go:build
      - rust:build
      - js:build

  build-all:
    desc: Build all components for all platforms
    deps:
      - go:build-all
      - build

  rust:clean:
    desc: Clean all build artifacts
    dir: ./plugin-rust-core
    cmd: cargo clean

  js:clean:
    desc: Clean build artifacts
    dir: ./plugin-js-api
    cmd: rm -rf ./dist

  clean:
    desc: Clean all build artifacts
    deps:
      - go:clean
      - rust:clean
      - js:clean
