version: '3'

includes:
  desktop:
    taskfile: ./desktop/Taskfile.yml
    dir: ./desktop
  mobile:
    taskfile: ./mobile/Taskfile.yml
    dir: ./mobile

tasks:
  build:
    desc: "Build all Go backend binaries"
    deps:
      - desktop:build
      - mobile:build

  clean:
    desc: "Clean all build artifacts"
    deps:
      - desktop:clean
      - mobile:clean

  mod-tidy:
    desc: "Run go mod tidy in all modules"
    deps:
      - desktop:mod-tidy
      - mobile:mod-tidy

  test:
    desc: "Run all Go tests"
    cmds:
      - go test ./...

  test-coverage:
    desc: "Run tests with coverage"
    cmds:
      - go test -cover ./...

  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: "Format Go code"
    cmds:
      - go fmt ./...
