version: 3

tasks:
  generate:
    desc: Generate code from protobuf definitions
    cmds:
      - buf generate --template ./proto/syncspace-api/buf.gen.yaml
      - buf generate --template ./proto/dispatch-transport/buf.gen.yaml
    sources:
      - proto/**/*.proto
      - proto/**/*.gen.yaml
      - buf.yaml
    generates:
      - ../plugin-go-backend/shared/proto/**/*.pb.go
      - ../plugin-go-backend/desktop/proto/**/*.pb.go
      - ../plugin-js-api/src/generated/**/*.ts

  lint:
    desc: Lint protobuf definitions
    cmd: buf lint

  breaking:
    desc: Check for breaking changes in protobuf definitions
    cmd: buf breaking --against '.git#branch=main'
