version: 3

tasks:
  generate-transport:
    desc: Generate transport code from protobuf
    cmds:
      - buf generate --template ./proto/dispatch-transport/buf.gen.yaml
    sources:
      - ./proto/**/*.proto
      - ./proto/**/*.gen.yaml
      - ./buf.yaml
    generates:
      - "{{.ROOT_DIR}}/plugin-go-backend/**/proto/**/*.pb.go"

  generate-syncspace:
    desc: Generate syncspace code from protobuf
    cmds:
      - buf generate --template ./proto/syncspace-api/buf.gen.yaml
      # Fix generated TypeScript code formatting
      - task: :api:fix
        vars:
          CLI_ARGS: "./src/generated"
    sources:
      - ./proto/**/*.proto
      - ./proto/**/*.gen.yaml
      - ./buf.yaml
      - ../plugin-js-api/scripts/generate_api.ts
    generates:
      - "{{.ROOT_DIR}}/plugin-go-backend/**/proto/**/*.pb.go"
      - "{{.ROOT_DIR}}/plugin-js-api/src/generated/**/*.ts"

  generate:
    desc: Generate all protobuf code
    deps:
      - generate-syncspace
      - generate-transport

  lint:
    desc: Lint protobuf definitions
    cmd: buf lint

  breaking:
    desc: Check for breaking changes in protobuf definitions
    cmd: buf breaking --against '.git#branch=main'

  clean:
    desc: Clean generated protobuf code
    cmds:
      - find ../plugin-go-backend -type f -path "*/proto/*.pb.go" -delete
      - find ../plugin-js-api -type f -path "*/src/generated/*_pb.ts" -delete
