// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: syncspace/v1/syncspace.proto

package syncspace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncStatus int32

const (
	SyncStatus_SYNC_STATUS_UNSPECIFIED SyncStatus = 0
	SyncStatus_SYNC_STATUS_IDLE        SyncStatus = 1
	SyncStatus_SYNC_STATUS_SYNCING     SyncStatus = 2
	SyncStatus_SYNC_STATUS_PAUSED      SyncStatus = 3
	SyncStatus_SYNC_STATUS_ERROR       SyncStatus = 4
)

// Enum value maps for SyncStatus.
var (
	SyncStatus_name = map[int32]string{
		0: "SYNC_STATUS_UNSPECIFIED",
		1: "SYNC_STATUS_IDLE",
		2: "SYNC_STATUS_SYNCING",
		3: "SYNC_STATUS_PAUSED",
		4: "SYNC_STATUS_ERROR",
	}
	SyncStatus_value = map[string]int32{
		"SYNC_STATUS_UNSPECIFIED": 0,
		"SYNC_STATUS_IDLE":        1,
		"SYNC_STATUS_SYNCING":     2,
		"SYNC_STATUS_PAUSED":      3,
		"SYNC_STATUS_ERROR":       4,
	}
)

func (x SyncStatus) Enum() *SyncStatus {
	p := new(SyncStatus)
	*p = x
	return p
}

func (x SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_syncspace_v1_syncspace_proto_enumTypes[0].Descriptor()
}

func (SyncStatus) Type() protoreflect.EnumType {
	return &file_syncspace_v1_syncspace_proto_enumTypes[0]
}

func (x SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStatus.Descriptor instead.
func (SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{0}
}

// Command represents a unified command for single-dispatch pattern
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // Command name (e.g., "createSpace", "getDocument")
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // Serialized request message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// CommandResponse represents the unified response
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // Serialized response message
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`     // Error message if operation failed (empty if success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataDir       string                 `protobuf:"bytes,1,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`                                                          // Directory for local storage
	NetworkId     string                 `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`                                                    // Any-Sync network ID
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                                       // Unique device identifier
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *InitRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *InitRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{3}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{4}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{5}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`                                                              // Unique space identifier
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Human-readable space name
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Space metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpaceRequest) Reset() {
	*x = CreateSpaceRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceRequest) ProtoMessage() {}

func (x *CreateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSpaceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *CreateSpaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSpaceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateSpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpaceResponse) Reset() {
	*x = CreateSpaceResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceResponse) ProtoMessage() {}

func (x *CreateSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceResponse.ProtoReflect.Descriptor instead.
func (*CreateSpaceResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSpaceResponse) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type JoinSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`             // Space identifier to join
	InviteToken   string                 `protobuf:"bytes,2,opt,name=invite_token,json=inviteToken,proto3" json:"invite_token,omitempty"` // Invitation token (if required)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSpaceRequest) Reset() {
	*x = JoinSpaceRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSpaceRequest) ProtoMessage() {}

func (x *JoinSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSpaceRequest.ProtoReflect.Descriptor instead.
func (*JoinSpaceRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{8}
}

func (x *JoinSpaceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *JoinSpaceRequest) GetInviteToken() string {
	if x != nil {
		return x.InviteToken
	}
	return ""
}

type JoinSpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSpaceResponse) Reset() {
	*x = JoinSpaceResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSpaceResponse) ProtoMessage() {}

func (x *JoinSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSpaceResponse.ProtoReflect.Descriptor instead.
func (*JoinSpaceResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{9}
}

func (x *JoinSpaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LeaveSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"` // Space identifier to leave
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSpaceRequest) Reset() {
	*x = LeaveSpaceRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSpaceRequest) ProtoMessage() {}

func (x *LeaveSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSpaceRequest.ProtoReflect.Descriptor instead.
func (*LeaveSpaceRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveSpaceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type LeaveSpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSpaceResponse) Reset() {
	*x = LeaveSpaceResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSpaceResponse) ProtoMessage() {}

func (x *LeaveSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSpaceResponse.ProtoReflect.Descriptor instead.
func (*LeaveSpaceResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{11}
}

func (x *LeaveSpaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListSpacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesRequest) Reset() {
	*x = ListSpacesRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesRequest) ProtoMessage() {}

func (x *ListSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesRequest.ProtoReflect.Descriptor instead.
func (*ListSpacesRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{12}
}

type ListSpacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spaces        []*SpaceInfo           `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesResponse) Reset() {
	*x = ListSpacesResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesResponse) ProtoMessage() {}

func (x *ListSpacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesResponse.ProtoReflect.Descriptor instead.
func (*ListSpacesResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{13}
}

func (x *ListSpacesResponse) GetSpaces() []*SpaceInfo {
	if x != nil {
		return x.Spaces
	}
	return nil
}

type SpaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	SyncStatus    SyncStatus             `protobuf:"varint,6,opt,name=sync_status,json=syncStatus,proto3,enum=syncspace.v1.SyncStatus" json:"sync_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceInfo) Reset() {
	*x = SpaceInfo{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceInfo) ProtoMessage() {}

func (x *SpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceInfo.ProtoReflect.Descriptor instead.
func (*SpaceInfo) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{14}
}

func (x *SpaceInfo) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *SpaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpaceInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SpaceInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SpaceInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *SpaceInfo) GetSyncStatus() SyncStatus {
	if x != nil {
		return x.SyncStatus
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

type DeleteSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSpaceRequest) Reset() {
	*x = DeleteSpaceRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpaceRequest) ProtoMessage() {}

func (x *DeleteSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteSpaceRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteSpaceRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type DeleteSpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSpaceResponse) Reset() {
	*x = DeleteSpaceResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpaceResponse) ProtoMessage() {}

func (x *DeleteSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteSpaceResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteSpaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`                                                     // Unique document identifier within space
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`                                                                       // Logical collection name (e.g., "notes", "tasks")
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                                                                   // Opaque document payload (application-defined format)
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Indexable metadata fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{17}
}

func (x *CreateDocumentRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *CreateDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreateDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CreateDocumentRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateDocumentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // Document version for optimistic locking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentResponse) Reset() {
	*x = CreateDocumentResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentResponse) ProtoMessage() {}

func (x *CreateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentResponse.ProtoReflect.Descriptor instead.
func (*CreateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{18}
}

func (x *CreateDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreateDocumentResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{19}
}

func (x *GetDocumentRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{20}
}

func (x *GetDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *GetDocumentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	SpaceId       string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Collection    string                 `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // Opaque payload
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{21}
}

func (x *Document) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Document) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *Document) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Document) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Document) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Document) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Document) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Document) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UpdateDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SpaceId         string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Data            []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpectedVersion int64                  `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // For optimistic locking (0 = skip check)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateDocumentRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateDocumentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateDocumentRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type UpdateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // New version after update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentResponse) Reset() {
	*x = UpdateDocumentResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentResponse) ProtoMessage() {}

func (x *UpdateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateDocumentResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteDocumentRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *DeleteDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Existed       bool                   `protobuf:"varint,1,opt,name=existed,proto3" json:"existed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteDocumentResponse) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"` // Filter by collection (empty = all)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`          // Max results (0 = no limit)
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`         // Pagination cursor (empty = first page)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{26}
}

func (x *ListDocumentsRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ListDocumentsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ListDocumentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDocumentsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*DocumentInfo        `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // Cursor for next page (empty = no more pages)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{27}
}

func (x *ListDocumentsResponse) GetDocuments() []*DocumentInfo {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type DocumentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentInfo) Reset() {
	*x = DocumentInfo{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentInfo) ProtoMessage() {}

func (x *DocumentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentInfo.ProtoReflect.Descriptor instead.
func (*DocumentInfo) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{28}
}

func (x *DocumentInfo) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentInfo) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DocumentInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DocumentInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DocumentInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DocumentInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type QueryDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Filters       []*QueryFilter         `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDocumentsRequest) Reset() {
	*x = QueryDocumentsRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDocumentsRequest) ProtoMessage() {}

func (x *QueryDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDocumentsRequest.ProtoReflect.Descriptor instead.
func (*QueryDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{29}
}

func (x *QueryDocumentsRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *QueryDocumentsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *QueryDocumentsRequest) GetFilters() []*QueryFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *QueryDocumentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryDocumentsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type QueryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`       // Metadata field name
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` // "eq", "ne", "gt", "gte", "lt", "lte", "contains"
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`       // Filter value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{30}
}

func (x *QueryFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *QueryFilter) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *QueryFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type QueryDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*DocumentInfo        `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDocumentsResponse) Reset() {
	*x = QueryDocumentsResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDocumentsResponse) ProtoMessage() {}

func (x *QueryDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDocumentsResponse.ProtoReflect.Descriptor instead.
func (*QueryDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{31}
}

func (x *QueryDocumentsResponse) GetDocuments() []*DocumentInfo {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *QueryDocumentsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type StartSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"` // Space to sync (empty = all spaces)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSyncRequest) Reset() {
	*x = StartSyncRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSyncRequest) ProtoMessage() {}

func (x *StartSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSyncRequest.ProtoReflect.Descriptor instead.
func (*StartSyncRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{32}
}

func (x *StartSyncRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type StartSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSyncResponse) Reset() {
	*x = StartSyncResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSyncResponse) ProtoMessage() {}

func (x *StartSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSyncResponse.ProtoReflect.Descriptor instead.
func (*StartSyncResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{33}
}

func (x *StartSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PauseSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"` // Space to pause (empty = all spaces)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSyncRequest) Reset() {
	*x = PauseSyncRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSyncRequest) ProtoMessage() {}

func (x *PauseSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSyncRequest.ProtoReflect.Descriptor instead.
func (*PauseSyncRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{34}
}

func (x *PauseSyncRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type PauseSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSyncResponse) Reset() {
	*x = PauseSyncResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSyncResponse) ProtoMessage() {}

func (x *PauseSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSyncResponse.ProtoReflect.Descriptor instead.
func (*PauseSyncResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{35}
}

func (x *PauseSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSyncStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"` // Space to query (empty = all spaces)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncStatusRequest) Reset() {
	*x = GetSyncStatusRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncStatusRequest) ProtoMessage() {}

func (x *GetSyncStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSyncStatusRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{36}
}

func (x *GetSyncStatusRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

type GetSyncStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*SpaceSyncStatus     `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncStatusResponse) Reset() {
	*x = GetSyncStatusResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncStatusResponse) ProtoMessage() {}

func (x *GetSyncStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSyncStatusResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{37}
}

func (x *GetSyncStatusResponse) GetStatuses() []*SpaceSyncStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type SpaceSyncStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpaceId        string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Status         SyncStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=syncspace.v1.SyncStatus" json:"status,omitempty"`
	LastSyncAt     int64                  `protobuf:"varint,3,opt,name=last_sync_at,json=lastSyncAt,proto3" json:"last_sync_at,omitempty"`           // Unix timestamp
	PendingChanges int32                  `protobuf:"varint,4,opt,name=pending_changes,json=pendingChanges,proto3" json:"pending_changes,omitempty"` // Number of local changes not yet synced
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                          // Last sync error (empty if no error)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpaceSyncStatus) Reset() {
	*x = SpaceSyncStatus{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceSyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceSyncStatus) ProtoMessage() {}

func (x *SpaceSyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceSyncStatus.ProtoReflect.Descriptor instead.
func (*SpaceSyncStatus) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{38}
}

func (x *SpaceSyncStatus) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *SpaceSyncStatus) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *SpaceSyncStatus) GetLastSyncAt() int64 {
	if x != nil {
		return x.LastSyncAt
	}
	return 0
}

func (x *SpaceSyncStatus) GetPendingChanges() int32 {
	if x != nil {
		return x.PendingChanges
	}
	return 0
}

func (x *SpaceSyncStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // Event types to subscribe to (empty = all)
	SpaceIds      []string               `protobuf:"bytes,2,rep,name=space_ids,json=spaceIds,proto3" json:"space_ids,omitempty"`       // Space IDs to filter by (empty = all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{39}
}

func (x *SubscribeRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *SubscribeRequest) GetSpaceIds() []string {
	if x != nil {
		return x.SpaceIds
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "document.created", "document.updated", "sync.status_changed", etc.
	SpaceId       string                 `protobuf:"bytes,3,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`      // Event-specific data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{40}
}

func (x *SubscribeResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SubscribeResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SubscribeResponse) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *SubscribeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SubscribeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DocumentCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentCreatedEvent) Reset() {
	*x = DocumentCreatedEvent{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentCreatedEvent) ProtoMessage() {}

func (x *DocumentCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentCreatedEvent.ProtoReflect.Descriptor instead.
func (*DocumentCreatedEvent) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{41}
}

func (x *DocumentCreatedEvent) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentCreatedEvent) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type DocumentUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	OldVersion    int64                  `protobuf:"varint,2,opt,name=old_version,json=oldVersion,proto3" json:"old_version,omitempty"`
	NewVersion    int64                  `protobuf:"varint,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentUpdatedEvent) Reset() {
	*x = DocumentUpdatedEvent{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUpdatedEvent) ProtoMessage() {}

func (x *DocumentUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUpdatedEvent.ProtoReflect.Descriptor instead.
func (*DocumentUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{42}
}

func (x *DocumentUpdatedEvent) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentUpdatedEvent) GetOldVersion() int64 {
	if x != nil {
		return x.OldVersion
	}
	return 0
}

func (x *DocumentUpdatedEvent) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

type DocumentDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentDeletedEvent) Reset() {
	*x = DocumentDeletedEvent{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentDeletedEvent) ProtoMessage() {}

func (x *DocumentDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentDeletedEvent.ProtoReflect.Descriptor instead.
func (*DocumentDeletedEvent) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{43}
}

func (x *DocumentDeletedEvent) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type SyncStatusChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldStatus     SyncStatus             `protobuf:"varint,1,opt,name=old_status,json=oldStatus,proto3,enum=syncspace.v1.SyncStatus" json:"old_status,omitempty"`
	NewStatus     SyncStatus             `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=syncspace.v1.SyncStatus" json:"new_status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStatusChangedEvent) Reset() {
	*x = SyncStatusChangedEvent{}
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatusChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatusChangedEvent) ProtoMessage() {}

func (x *SyncStatusChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_syncspace_v1_syncspace_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatusChangedEvent.ProtoReflect.Descriptor instead.
func (*SyncStatusChangedEvent) Descriptor() ([]byte, []int) {
	return file_syncspace_v1_syncspace_proto_rawDescGZIP(), []int{44}
}

func (x *SyncStatusChangedEvent) GetOldStatus() SyncStatus {
	if x != nil {
		return x.OldStatus
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *SyncStatusChangedEvent) GetNewStatus() SyncStatus {
	if x != nil {
		return x.NewStatus
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *SyncStatusChangedEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_syncspace_v1_syncspace_proto protoreflect.FileDescriptor

const file_syncspace_v1_syncspace_proto_rawDesc = "" +
	"\n" +
	"\x1csyncspace/v1/syncspace.proto\x12\fsyncspace.v1\"7\n" +
	"\aCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"A\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xde\x01\n" +
	"\vInitRequest\x12\x19\n" +
	"\bdata_dir\x18\x01 \x01(\tR\adataDir\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12=\n" +
	"\x06config\x18\x04 \x03(\v2%.syncspace.v1.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x11\n" +
	"\x0fShutdownRequest\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xcc\x01\n" +
	"\x12CreateSpaceRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12J\n" +
	"\bmetadata\x18\x03 \x03(\v2..syncspace.v1.CreateSpaceRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x13CreateSpaceResponse\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\"P\n" +
	"\x10JoinSpaceRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12!\n" +
	"\finvite_token\x18\x02 \x01(\tR\vinviteToken\"-\n" +
	"\x11JoinSpaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x11LeaveSpaceRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\".\n" +
	"\x12LeaveSpaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11ListSpacesRequest\"E\n" +
	"\x12ListSpacesResponse\x12/\n" +
	"\x06spaces\x18\x01 \x03(\v2\x17.syncspace.v1.SpaceInfoR\x06spaces\"\xb3\x02\n" +
	"\tSpaceInfo\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12A\n" +
	"\bmetadata\x18\x03 \x03(\v2%.syncspace.v1.SpaceInfo.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x129\n" +
	"\vsync_status\x18\x06 \x01(\x0e2\x18.syncspace.v1.SyncStatusR\n" +
	"syncStatus\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x12DeleteSpaceRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\"/\n" +
	"\x13DeleteSpaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x93\x02\n" +
	"\x15CreateDocumentRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12M\n" +
	"\bmetadata\x18\x05 \x03(\v21.syncspace.v1.CreateDocumentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x16CreateDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"P\n" +
	"\x12GetDocumentRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\"_\n" +
	"\x13GetDocumentResponse\x122\n" +
	"\bdocument\x18\x01 \x01(\v2\x16.syncspace.v1.DocumentR\bdocument\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xd1\x02\n" +
	"\bDocument\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12\x1e\n" +
	"\n" +
	"collection\x18\x03 \x01(\tR\n" +
	"collection\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12@\n" +
	"\bmetadata\x18\x05 \x03(\v2$.syncspace.v1.Document.MetadataEntryR\bmetadata\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x02\n" +
	"\x15UpdateDocumentRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12M\n" +
	"\bmetadata\x18\x04 \x03(\v21.syncspace.v1.UpdateDocumentRequest.MetadataEntryR\bmetadata\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x03R\x0fexpectedVersion\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x16UpdateDocumentResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"S\n" +
	"\x15DeleteDocumentRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\"2\n" +
	"\x16DeleteDocumentResponse\x12\x18\n" +
	"\aexisted\x18\x01 \x01(\bR\aexisted\"\x7f\n" +
	"\x14ListDocumentsRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"r\n" +
	"\x15ListDocumentsResponse\x128\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1a.syncspace.v1.DocumentInfoR\tdocuments\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xaa\x02\n" +
	"\fDocumentInfo\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.syncspace.v1.DocumentInfo.MetadataEntryR\bmetadata\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\x15QueryDocumentsRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x123\n" +
	"\afilters\x18\x03 \x03(\v2\x19.syncspace.v1.QueryFilterR\afilters\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"U\n" +
	"\vQueryFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"s\n" +
	"\x16QueryDocumentsResponse\x128\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1a.syncspace.v1.DocumentInfoR\tdocuments\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"-\n" +
	"\x10StartSyncRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\"-\n" +
	"\x11StartSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x10PauseSyncRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\"-\n" +
	"\x11PauseSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x14GetSyncStatusRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\"R\n" +
	"\x15GetSyncStatusResponse\x129\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1d.syncspace.v1.SpaceSyncStatusR\bstatuses\"\xbf\x01\n" +
	"\x0fSpaceSyncStatus\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.syncspace.v1.SyncStatusR\x06status\x12 \n" +
	"\flast_sync_at\x18\x03 \x01(\x03R\n" +
	"lastSyncAt\x12'\n" +
	"\x0fpending_changes\x18\x04 \x01(\x05R\x0ependingChanges\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"P\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\x12\x1b\n" +
	"\tspace_ids\x18\x02 \x03(\tR\bspaceIds\"\xa0\x01\n" +
	"\x11SubscribeResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x19\n" +
	"\bspace_id\x18\x03 \x01(\tR\aspaceId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"W\n" +
	"\x14DocumentCreatedEvent\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"y\n" +
	"\x14DocumentUpdatedEvent\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vold_version\x18\x02 \x01(\x03R\n" +
	"oldVersion\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\x03R\n" +
	"newVersion\"7\n" +
	"\x14DocumentDeletedEvent\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"\xa0\x01\n" +
	"\x16SyncStatusChangedEvent\x127\n" +
	"\n" +
	"old_status\x18\x01 \x01(\x0e2\x18.syncspace.v1.SyncStatusR\toldStatus\x127\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x18.syncspace.v1.SyncStatusR\tnewStatus\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\x87\x01\n" +
	"\n" +
	"SyncStatus\x12\x1b\n" +
	"\x17SYNC_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SYNC_STATUS_IDLE\x10\x01\x12\x17\n" +
	"\x13SYNC_STATUS_SYNCING\x10\x02\x12\x16\n" +
	"\x12SYNC_STATUS_PAUSED\x10\x03\x12\x15\n" +
	"\x11SYNC_STATUS_ERROR\x10\x042\x9c\v\n" +
	"\x10SyncSpaceService\x12=\n" +
	"\x04Init\x12\x19.syncspace.v1.InitRequest\x1a\x1a.syncspace.v1.InitResponse\x12I\n" +
	"\bShutdown\x12\x1d.syncspace.v1.ShutdownRequest\x1a\x1e.syncspace.v1.ShutdownResponse\x12R\n" +
	"\vCreateSpace\x12 .syncspace.v1.CreateSpaceRequest\x1a!.syncspace.v1.CreateSpaceResponse\x12L\n" +
	"\tJoinSpace\x12\x1e.syncspace.v1.JoinSpaceRequest\x1a\x1f.syncspace.v1.JoinSpaceResponse\x12O\n" +
	"\n" +
	"LeaveSpace\x12\x1f.syncspace.v1.LeaveSpaceRequest\x1a .syncspace.v1.LeaveSpaceResponse\x12O\n" +
	"\n" +
	"ListSpaces\x12\x1f.syncspace.v1.ListSpacesRequest\x1a .syncspace.v1.ListSpacesResponse\x12R\n" +
	"\vDeleteSpace\x12 .syncspace.v1.DeleteSpaceRequest\x1a!.syncspace.v1.DeleteSpaceResponse\x12[\n" +
	"\x0eCreateDocument\x12#.syncspace.v1.CreateDocumentRequest\x1a$.syncspace.v1.CreateDocumentResponse\x12R\n" +
	"\vGetDocument\x12 .syncspace.v1.GetDocumentRequest\x1a!.syncspace.v1.GetDocumentResponse\x12[\n" +
	"\x0eUpdateDocument\x12#.syncspace.v1.UpdateDocumentRequest\x1a$.syncspace.v1.UpdateDocumentResponse\x12[\n" +
	"\x0eDeleteDocument\x12#.syncspace.v1.DeleteDocumentRequest\x1a$.syncspace.v1.DeleteDocumentResponse\x12X\n" +
	"\rListDocuments\x12\".syncspace.v1.ListDocumentsRequest\x1a#.syncspace.v1.ListDocumentsResponse\x12[\n" +
	"\x0eQueryDocuments\x12#.syncspace.v1.QueryDocumentsRequest\x1a$.syncspace.v1.QueryDocumentsResponse\x12L\n" +
	"\tStartSync\x12\x1e.syncspace.v1.StartSyncRequest\x1a\x1f.syncspace.v1.StartSyncResponse\x12L\n" +
	"\tPauseSync\x12\x1e.syncspace.v1.PauseSyncRequest\x1a\x1f.syncspace.v1.PauseSyncResponse\x12X\n" +
	"\rGetSyncStatus\x12\".syncspace.v1.GetSyncStatusRequest\x1a#.syncspace.v1.GetSyncStatusResponse\x12N\n" +
	"\tSubscribe\x12\x1e.syncspace.v1.SubscribeRequest\x1a\x1f.syncspace.v1.SubscribeResponse0\x01B\xa8\x01\n" +
	"\x10com.syncspace.v1B\x0eSyncspaceProtoP\x01Z3anysync-backend/shared/proto/syncspace/v1;syncspace\xa2\x02\x03SXX\xaa\x02\fSyncspace.V1\xca\x02\fSyncspace\\V1\xe2\x02\x18Syncspace\\V1\\GPBMetadata\xea\x02\rSyncspace::V1b\x06proto3"

var (
	file_syncspace_v1_syncspace_proto_rawDescOnce sync.Once
	file_syncspace_v1_syncspace_proto_rawDescData []byte
)

func file_syncspace_v1_syncspace_proto_rawDescGZIP() []byte {
	file_syncspace_v1_syncspace_proto_rawDescOnce.Do(func() {
		file_syncspace_v1_syncspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_syncspace_v1_syncspace_proto_rawDesc), len(file_syncspace_v1_syncspace_proto_rawDesc)))
	})
	return file_syncspace_v1_syncspace_proto_rawDescData
}

var file_syncspace_v1_syncspace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_syncspace_v1_syncspace_proto_msgTypes = make([]protoimpl.MessageInfo, 52)
var file_syncspace_v1_syncspace_proto_goTypes = []any{
	(SyncStatus)(0),                // 0: syncspace.v1.SyncStatus
	(*Command)(nil),                // 1: syncspace.v1.Command
	(*CommandResponse)(nil),        // 2: syncspace.v1.CommandResponse
	(*InitRequest)(nil),            // 3: syncspace.v1.InitRequest
	(*InitResponse)(nil),           // 4: syncspace.v1.InitResponse
	(*ShutdownRequest)(nil),        // 5: syncspace.v1.ShutdownRequest
	(*ShutdownResponse)(nil),       // 6: syncspace.v1.ShutdownResponse
	(*CreateSpaceRequest)(nil),     // 7: syncspace.v1.CreateSpaceRequest
	(*CreateSpaceResponse)(nil),    // 8: syncspace.v1.CreateSpaceResponse
	(*JoinSpaceRequest)(nil),       // 9: syncspace.v1.JoinSpaceRequest
	(*JoinSpaceResponse)(nil),      // 10: syncspace.v1.JoinSpaceResponse
	(*LeaveSpaceRequest)(nil),      // 11: syncspace.v1.LeaveSpaceRequest
	(*LeaveSpaceResponse)(nil),     // 12: syncspace.v1.LeaveSpaceResponse
	(*ListSpacesRequest)(nil),      // 13: syncspace.v1.ListSpacesRequest
	(*ListSpacesResponse)(nil),     // 14: syncspace.v1.ListSpacesResponse
	(*SpaceInfo)(nil),              // 15: syncspace.v1.SpaceInfo
	(*DeleteSpaceRequest)(nil),     // 16: syncspace.v1.DeleteSpaceRequest
	(*DeleteSpaceResponse)(nil),    // 17: syncspace.v1.DeleteSpaceResponse
	(*CreateDocumentRequest)(nil),  // 18: syncspace.v1.CreateDocumentRequest
	(*CreateDocumentResponse)(nil), // 19: syncspace.v1.CreateDocumentResponse
	(*GetDocumentRequest)(nil),     // 20: syncspace.v1.GetDocumentRequest
	(*GetDocumentResponse)(nil),    // 21: syncspace.v1.GetDocumentResponse
	(*Document)(nil),               // 22: syncspace.v1.Document
	(*UpdateDocumentRequest)(nil),  // 23: syncspace.v1.UpdateDocumentRequest
	(*UpdateDocumentResponse)(nil), // 24: syncspace.v1.UpdateDocumentResponse
	(*DeleteDocumentRequest)(nil),  // 25: syncspace.v1.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil), // 26: syncspace.v1.DeleteDocumentResponse
	(*ListDocumentsRequest)(nil),   // 27: syncspace.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),  // 28: syncspace.v1.ListDocumentsResponse
	(*DocumentInfo)(nil),           // 29: syncspace.v1.DocumentInfo
	(*QueryDocumentsRequest)(nil),  // 30: syncspace.v1.QueryDocumentsRequest
	(*QueryFilter)(nil),            // 31: syncspace.v1.QueryFilter
	(*QueryDocumentsResponse)(nil), // 32: syncspace.v1.QueryDocumentsResponse
	(*StartSyncRequest)(nil),       // 33: syncspace.v1.StartSyncRequest
	(*StartSyncResponse)(nil),      // 34: syncspace.v1.StartSyncResponse
	(*PauseSyncRequest)(nil),       // 35: syncspace.v1.PauseSyncRequest
	(*PauseSyncResponse)(nil),      // 36: syncspace.v1.PauseSyncResponse
	(*GetSyncStatusRequest)(nil),   // 37: syncspace.v1.GetSyncStatusRequest
	(*GetSyncStatusResponse)(nil),  // 38: syncspace.v1.GetSyncStatusResponse
	(*SpaceSyncStatus)(nil),        // 39: syncspace.v1.SpaceSyncStatus
	(*SubscribeRequest)(nil),       // 40: syncspace.v1.SubscribeRequest
	(*SubscribeResponse)(nil),      // 41: syncspace.v1.SubscribeResponse
	(*DocumentCreatedEvent)(nil),   // 42: syncspace.v1.DocumentCreatedEvent
	(*DocumentUpdatedEvent)(nil),   // 43: syncspace.v1.DocumentUpdatedEvent
	(*DocumentDeletedEvent)(nil),   // 44: syncspace.v1.DocumentDeletedEvent
	(*SyncStatusChangedEvent)(nil), // 45: syncspace.v1.SyncStatusChangedEvent
	nil,                            // 46: syncspace.v1.InitRequest.ConfigEntry
	nil,                            // 47: syncspace.v1.CreateSpaceRequest.MetadataEntry
	nil,                            // 48: syncspace.v1.SpaceInfo.MetadataEntry
	nil,                            // 49: syncspace.v1.CreateDocumentRequest.MetadataEntry
	nil,                            // 50: syncspace.v1.Document.MetadataEntry
	nil,                            // 51: syncspace.v1.UpdateDocumentRequest.MetadataEntry
	nil,                            // 52: syncspace.v1.DocumentInfo.MetadataEntry
}
var file_syncspace_v1_syncspace_proto_depIdxs = []int32{
	46, // 0: syncspace.v1.InitRequest.config:type_name -> syncspace.v1.InitRequest.ConfigEntry
	47, // 1: syncspace.v1.CreateSpaceRequest.metadata:type_name -> syncspace.v1.CreateSpaceRequest.MetadataEntry
	15, // 2: syncspace.v1.ListSpacesResponse.spaces:type_name -> syncspace.v1.SpaceInfo
	48, // 3: syncspace.v1.SpaceInfo.metadata:type_name -> syncspace.v1.SpaceInfo.MetadataEntry
	0,  // 4: syncspace.v1.SpaceInfo.sync_status:type_name -> syncspace.v1.SyncStatus
	49, // 5: syncspace.v1.CreateDocumentRequest.metadata:type_name -> syncspace.v1.CreateDocumentRequest.MetadataEntry
	22, // 6: syncspace.v1.GetDocumentResponse.document:type_name -> syncspace.v1.Document
	50, // 7: syncspace.v1.Document.metadata:type_name -> syncspace.v1.Document.MetadataEntry
	51, // 8: syncspace.v1.UpdateDocumentRequest.metadata:type_name -> syncspace.v1.UpdateDocumentRequest.MetadataEntry
	29, // 9: syncspace.v1.ListDocumentsResponse.documents:type_name -> syncspace.v1.DocumentInfo
	52, // 10: syncspace.v1.DocumentInfo.metadata:type_name -> syncspace.v1.DocumentInfo.MetadataEntry
	31, // 11: syncspace.v1.QueryDocumentsRequest.filters:type_name -> syncspace.v1.QueryFilter
	29, // 12: syncspace.v1.QueryDocumentsResponse.documents:type_name -> syncspace.v1.DocumentInfo
	39, // 13: syncspace.v1.GetSyncStatusResponse.statuses:type_name -> syncspace.v1.SpaceSyncStatus
	0,  // 14: syncspace.v1.SpaceSyncStatus.status:type_name -> syncspace.v1.SyncStatus
	0,  // 15: syncspace.v1.SyncStatusChangedEvent.old_status:type_name -> syncspace.v1.SyncStatus
	0,  // 16: syncspace.v1.SyncStatusChangedEvent.new_status:type_name -> syncspace.v1.SyncStatus
	3,  // 17: syncspace.v1.SyncSpaceService.Init:input_type -> syncspace.v1.InitRequest
	5,  // 18: syncspace.v1.SyncSpaceService.Shutdown:input_type -> syncspace.v1.ShutdownRequest
	7,  // 19: syncspace.v1.SyncSpaceService.CreateSpace:input_type -> syncspace.v1.CreateSpaceRequest
	9,  // 20: syncspace.v1.SyncSpaceService.JoinSpace:input_type -> syncspace.v1.JoinSpaceRequest
	11, // 21: syncspace.v1.SyncSpaceService.LeaveSpace:input_type -> syncspace.v1.LeaveSpaceRequest
	13, // 22: syncspace.v1.SyncSpaceService.ListSpaces:input_type -> syncspace.v1.ListSpacesRequest
	16, // 23: syncspace.v1.SyncSpaceService.DeleteSpace:input_type -> syncspace.v1.DeleteSpaceRequest
	18, // 24: syncspace.v1.SyncSpaceService.CreateDocument:input_type -> syncspace.v1.CreateDocumentRequest
	20, // 25: syncspace.v1.SyncSpaceService.GetDocument:input_type -> syncspace.v1.GetDocumentRequest
	23, // 26: syncspace.v1.SyncSpaceService.UpdateDocument:input_type -> syncspace.v1.UpdateDocumentRequest
	25, // 27: syncspace.v1.SyncSpaceService.DeleteDocument:input_type -> syncspace.v1.DeleteDocumentRequest
	27, // 28: syncspace.v1.SyncSpaceService.ListDocuments:input_type -> syncspace.v1.ListDocumentsRequest
	30, // 29: syncspace.v1.SyncSpaceService.QueryDocuments:input_type -> syncspace.v1.QueryDocumentsRequest
	33, // 30: syncspace.v1.SyncSpaceService.StartSync:input_type -> syncspace.v1.StartSyncRequest
	35, // 31: syncspace.v1.SyncSpaceService.PauseSync:input_type -> syncspace.v1.PauseSyncRequest
	37, // 32: syncspace.v1.SyncSpaceService.GetSyncStatus:input_type -> syncspace.v1.GetSyncStatusRequest
	40, // 33: syncspace.v1.SyncSpaceService.Subscribe:input_type -> syncspace.v1.SubscribeRequest
	4,  // 34: syncspace.v1.SyncSpaceService.Init:output_type -> syncspace.v1.InitResponse
	6,  // 35: syncspace.v1.SyncSpaceService.Shutdown:output_type -> syncspace.v1.ShutdownResponse
	8,  // 36: syncspace.v1.SyncSpaceService.CreateSpace:output_type -> syncspace.v1.CreateSpaceResponse
	10, // 37: syncspace.v1.SyncSpaceService.JoinSpace:output_type -> syncspace.v1.JoinSpaceResponse
	12, // 38: syncspace.v1.SyncSpaceService.LeaveSpace:output_type -> syncspace.v1.LeaveSpaceResponse
	14, // 39: syncspace.v1.SyncSpaceService.ListSpaces:output_type -> syncspace.v1.ListSpacesResponse
	17, // 40: syncspace.v1.SyncSpaceService.DeleteSpace:output_type -> syncspace.v1.DeleteSpaceResponse
	19, // 41: syncspace.v1.SyncSpaceService.CreateDocument:output_type -> syncspace.v1.CreateDocumentResponse
	21, // 42: syncspace.v1.SyncSpaceService.GetDocument:output_type -> syncspace.v1.GetDocumentResponse
	24, // 43: syncspace.v1.SyncSpaceService.UpdateDocument:output_type -> syncspace.v1.UpdateDocumentResponse
	26, // 44: syncspace.v1.SyncSpaceService.DeleteDocument:output_type -> syncspace.v1.DeleteDocumentResponse
	28, // 45: syncspace.v1.SyncSpaceService.ListDocuments:output_type -> syncspace.v1.ListDocumentsResponse
	32, // 46: syncspace.v1.SyncSpaceService.QueryDocuments:output_type -> syncspace.v1.QueryDocumentsResponse
	34, // 47: syncspace.v1.SyncSpaceService.StartSync:output_type -> syncspace.v1.StartSyncResponse
	36, // 48: syncspace.v1.SyncSpaceService.PauseSync:output_type -> syncspace.v1.PauseSyncResponse
	38, // 49: syncspace.v1.SyncSpaceService.GetSyncStatus:output_type -> syncspace.v1.GetSyncStatusResponse
	41, // 50: syncspace.v1.SyncSpaceService.Subscribe:output_type -> syncspace.v1.SubscribeResponse
	34, // [34:51] is the sub-list for method output_type
	17, // [17:34] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_syncspace_v1_syncspace_proto_init() }
func file_syncspace_v1_syncspace_proto_init() {
	if File_syncspace_v1_syncspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_syncspace_v1_syncspace_proto_rawDesc), len(file_syncspace_v1_syncspace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   52,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_syncspace_v1_syncspace_proto_goTypes,
		DependencyIndexes: file_syncspace_v1_syncspace_proto_depIdxs,
		EnumInfos:         file_syncspace_v1_syncspace_proto_enumTypes,
		MessageInfos:      file_syncspace_v1_syncspace_proto_msgTypes,
	}.Build()
	File_syncspace_v1_syncspace_proto = out.File
	file_syncspace_v1_syncspace_proto_goTypes = nil
	file_syncspace_v1_syncspace_proto_depIdxs = nil
}
