// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: transport/v1/transport.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Init request with configuration
type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Storage directory path
	StoragePath string `protobuf:"bytes,1,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	// Network ID for Any-Sync
	NetworkId string `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Optional configuration JSON
	ConfigJson    string `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_transport_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_transport_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *InitRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *InitRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success message or empty
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_transport_v1_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_v1_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_transport_v1_transport_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Command request with operation name and serialized data
type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command name (e.g., "createSpace", "getDocument")
	Cmd string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// Serialized request data (protobuf bytes from syncspace.proto messages)
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_transport_v1_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_v1_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_transport_v1_transport_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *CommandRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized response data (protobuf bytes from syncspace.proto messages)
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_transport_v1_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_v1_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_transport_v1_transport_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Subscribe to event stream
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event filter (optional, empty means all events)
	EventTypes    []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_transport_v1_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_v1_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_transport_v1_transport_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// Event notification (streaming response)
type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type (e.g., "documentChanged", "syncStatusChanged")
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Serialized event data
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Timestamp (Unix milliseconds)
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_transport_v1_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_v1_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_transport_v1_transport_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubscribeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubscribeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Shutdown request
type ShutdownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Graceful shutdown timeout in milliseconds
	TimeoutMs     int64 `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_transport_v1_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_v1_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_transport_v1_transport_proto_rawDescGZIP(), []int{6}
}

func (x *ShutdownRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ShutdownResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_transport_v1_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_v1_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_transport_v1_transport_proto_rawDescGZIP(), []int{7}
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_transport_v1_transport_proto protoreflect.FileDescriptor

const file_transport_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x1ctransport/v1/transport.proto\x12\ftransport.v1\"p\n" +
	"\vInitRequest\x12!\n" +
	"\fstorage_path\x18\x01 \x01(\tR\vstoragePath\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\"(\n" +
	"\fInitResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x0eCommandRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"%\n" +
	"\x0fCommandResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"3\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"Y\n" +
	"\x11SubscribeResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"0\n" +
	"\x0fShutdownRequest\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\x03R\ttimeoutMs\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb4\x02\n" +
	"\x10TransportService\x12=\n" +
	"\x04Init\x12\x19.transport.v1.InitRequest\x1a\x1a.transport.v1.InitResponse\x12F\n" +
	"\aCommand\x12\x1c.transport.v1.CommandRequest\x1a\x1d.transport.v1.CommandResponse\x12N\n" +
	"\tSubscribe\x12\x1e.transport.v1.SubscribeRequest\x1a\x1f.transport.v1.SubscribeResponse0\x01\x12I\n" +
	"\bShutdown\x12\x1d.transport.v1.ShutdownRequest\x1a\x1e.transport.v1.ShutdownResponseB\x9f\x01\n" +
	"\x10com.transport.v1B\x0eTransportProtoP\x01Z*anysync-backend/desktop/proto/v1;transport\xa2\x02\x03TXX\xaa\x02\fTransport.V1\xca\x02\fTransport\\V1\xe2\x02\x18Transport\\V1\\GPBMetadata\xea\x02\rTransport::V1b\x06proto3"

var (
	file_transport_v1_transport_proto_rawDescOnce sync.Once
	file_transport_v1_transport_proto_rawDescData []byte
)

func file_transport_v1_transport_proto_rawDescGZIP() []byte {
	file_transport_v1_transport_proto_rawDescOnce.Do(func() {
		file_transport_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_v1_transport_proto_rawDesc), len(file_transport_v1_transport_proto_rawDesc)))
	})
	return file_transport_v1_transport_proto_rawDescData
}

var file_transport_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_transport_v1_transport_proto_goTypes = []any{
	(*InitRequest)(nil),       // 0: transport.v1.InitRequest
	(*InitResponse)(nil),      // 1: transport.v1.InitResponse
	(*CommandRequest)(nil),    // 2: transport.v1.CommandRequest
	(*CommandResponse)(nil),   // 3: transport.v1.CommandResponse
	(*SubscribeRequest)(nil),  // 4: transport.v1.SubscribeRequest
	(*SubscribeResponse)(nil), // 5: transport.v1.SubscribeResponse
	(*ShutdownRequest)(nil),   // 6: transport.v1.ShutdownRequest
	(*ShutdownResponse)(nil),  // 7: transport.v1.ShutdownResponse
}
var file_transport_v1_transport_proto_depIdxs = []int32{
	0, // 0: transport.v1.TransportService.Init:input_type -> transport.v1.InitRequest
	2, // 1: transport.v1.TransportService.Command:input_type -> transport.v1.CommandRequest
	4, // 2: transport.v1.TransportService.Subscribe:input_type -> transport.v1.SubscribeRequest
	6, // 3: transport.v1.TransportService.Shutdown:input_type -> transport.v1.ShutdownRequest
	1, // 4: transport.v1.TransportService.Init:output_type -> transport.v1.InitResponse
	3, // 5: transport.v1.TransportService.Command:output_type -> transport.v1.CommandResponse
	5, // 6: transport.v1.TransportService.Subscribe:output_type -> transport.v1.SubscribeResponse
	7, // 7: transport.v1.TransportService.Shutdown:output_type -> transport.v1.ShutdownResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_v1_transport_proto_init() }
func file_transport_v1_transport_proto_init() {
	if File_transport_v1_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_v1_transport_proto_rawDesc), len(file_transport_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_v1_transport_proto_goTypes,
		DependencyIndexes: file_transport_v1_transport_proto_depIdxs,
		MessageInfos:      file_transport_v1_transport_proto_msgTypes,
	}.Build()
	File_transport_v1_transport_proto = out.File
	file_transport_v1_transport_proto_goTypes = nil
	file_transport_v1_transport_proto_depIdxs = nil
}
