version: "3"

vars:
  BINARIES_DIR: ../../binaries

tasks:
  default:
    deps: [build]

  gomobile-setup:
    desc: Install gomobile toolchain
    internal: true
    silent: true
    run: once
    status:
      - "! command -q gomobile"
    cmds:
      - go install golang.org/x/mobile/cmd/gomobile@latest
      - gomobile init

  build-android:
    desc: Build the Android .aar file with gomobile
    preconditions:
      - 'test -n "$ANDROID_HOME"'
    deps:
      - gomobile-setup
    cmds:
      - gomobile bind -target=android -androidapi=21 -o '{{.BINARIES_DIR}}/any-sync-android.aar' .
    sources:
      - ./go.*
      - ./**/*.go
      - ../shared/**/*.go
    generates:
      - "{{.BINARIES_DIR}}/any-sync-android*"

  build:
    desc: "Build mobile binaries"
    aliases: [build-all]
    deps:
      - build-android
      # - build-ios

  clean:
    desc: "Clean mobile build artifacts"
    cmds:
      - rm -rf '{{.BINARIES_DIR}}/any-sync-android*'

  mod-tidy:
    desc: "Clean and verify Go modules"
    cmd: go mod tidy
