version: "3"

vars:
  BINARIES_DIR: "{{.ROOT_DIR}}/binaries"
  BINARY_PREFIX: any-sync

tasks:
  default:
    deps: [build]

  gomobile-setup:
    desc: Install gomobile toolchain
    internal: true
    run: once
    status:
      - "! which gomobile"
    cmds:
      - go install golang.org/x/mobile/cmd/gomobile@latest
      - gomobile init

  build:android:
    desc: Build the Android .aar file with gomobile
    preconditions:
      - 'test -n "$ANDROID_HOME"'
    deps:
      - gomobile-setup
    vars:
      EXT: .aar
      NAME: "{{.BINARY_PREFIX}}-android{{.EXT}}"
      BINARY: "{{joinPath .BINARIES_DIR .NAME}}"
    label: "{{.TASK}}"
    cmds:
      - mkdir -p '{{.BINARIES_DIR}}'
      - gomobile bind -target=android -androidapi=21 -o '{{.BINARY}}' .
      - ls -la '{{.BINARIES_DIR}}'
    sources:
      - ./**/*
      - ../shared/**/*
    generates:
      - "{{.BINARY}}"

  build:ios:
    desc: Build the iOS .xcframework file with gomobile
    deps:
      - gomobile-setup
    vars:
      EXT: .xcframework
      NAME: "AnySync{{.EXT}}"
      BINARY: "{{joinPath .BINARIES_DIR .NAME}}"
    label: "{{.TASK}}"
    cmds:
      - mkdir -p '{{.BINARIES_DIR}}'
      - gomobile bind -target=ios,iossimulator,macos -o '{{.BINARY}}' .
      - ls -la '{{.BINARIES_DIR}}'
    sources:
      - ./**/*
      - ../shared/**/*
    generates:
      - "{{.BINARY}}"

  build:
    desc: Build mobile binaries for current platform
    deps:
      - build:android
      - build:ios

  build-all:
    desc: "Build all mobile binaries"
    deps:
      - build:android
      - build:ios

  test:
    desc: "Run Go tests"
    cmd: go test ./...

  clean:
    desc: "Clean mobile build artifacts"
    cmds:
      - rm -rf '{{.BINARIES_DIR}}/any-sync-android*'
      - rm -rf '{{.BINARIES_DIR}}/any-sync-ios*'

  mod-tidy:
    desc: "Clean and verify Go modules"
    cmd: go mod tidy
