version: 3

tasks:
  install:
    desc: Install npm dependencies
    cmd: bun install
    internal: true
    run: once

  build:
    desc: Build CJS/ESM artifacts
    deps:
      - install
      - :buf:generate-syncspace
    cmd: bun run build
    run: once

  typecheck:
    desc: Type check TypeScript code
    deps:
      - install
      - :buf:generate-syncspace
    cmd: bun run tsc --noEmit --allowJs --checkJs --strict --target esnext --moduleResolution bundler ./src/*.ts

  check:
    desc: Run linting and formatting checks
    cmd: "bun run biome {{if .CI}}ci{{else}}check{{end}} {{.CLI_ARGS}}"

  format:
    desc: Fix formatting
    cmd: bun run biome format --write {{.CLI_ARGS}}

  fix:
    desc: Fix linting and formatting issues
    cmd: bun run biome check --write {{.CLI_ARGS}}

  clean:
    desc: Clean build artifacts
    cmd: rm -rf ./dist
