version: 3

tasks:
  install:
    desc: Install npm dependencies
    cmd: bun install
    internal: true
    run: once

  build:
    desc: Build CJS/ESM artifacts
    deps:
      - install
    cmd: bun run build
    run: once

  typecheck:
    desc: Type check TypeScript code
    deps:
      - install
    cmd: bun run tsc --noEmit --allowJs --checkJs --strict --target esnext --moduleResolution bundler ./src/*.ts

  clean:
    desc: Clean build artifacts
    cmd: rm -rf ./dist
