version: 3

includes:
  desktop:
    taskfile: ./desktop/Taskfile.yml
    dir: ./desktop
  mobile:
    taskfile: ./mobile/Taskfile.yml
    dir: ./mobile
  shared:
    taskfile: ./shared/Taskfile.yml
    dir: ./shared

tasks:
  build:
    desc: Build Go backend binaries for the current platform
    deps:
      - desktop:build

  build-all:
    desc: Build Go backend binaries for all platforms
    deps:
      - desktop:build-all
      - mobile:build-all
    cmd: ls -ogh {{.BINARIES_DIR}}

  build-apple:
    desc: Build Go backend binaries for Apple platforms
    deps:
      - desktop:build:macos
      - mobile:build:ios

  build-non-apple:
    desc: Build Go backend binaries for non-Apple platforms
    deps:
      - desktop:build:linux
      - desktop:build:windows
      - mobile:build:android

  clean:
    desc: Clean all build artifacts
    deps:
      - desktop:clean
      - mobile:clean

  test:
    desc: Run all Go tests across modules
    deps:
      - shared:test
      - desktop:test
      - mobile:test

  lint:
    desc: Run golangci-lint
    cmd: golangci-lint run ./...

  fmt:
    desc: Format Go code
    cmd: go fmt ./...

  work-sync:
    desc: Sync go.work with module dependencies
    cmd: go work sync

  mod-tidy:
    desc: Run go mod tidy in workspace
    deps:
      - work-sync
    cmds:
      - go mod tidy -C shared
      - go mod tidy -C desktop
      - go mod tidy -C mobile
